### ISSUE TITLE
Object has no attribute 'stream'

### ISSUE THREAD

**Issue by SaibotC** [olegchomp/TDDepthAnything#10]
Running windows with cuda 11.8. I'm getting this error. 

`Name: /project1/TDDepthAnything
Type: Base COMP
Loaded from: C:/Projects/TDDepthAnything/TDDepthAnything.tox Children: 11
Total Cooks: 4
CPU Cook Time: 289.303 ms (~289.303 ms ) (CPU Cook Time not measured on previous cook) GPU Cook Time: 0.000 ms
Cook Frame: 369 (/local/time/clock)
Children CPU Cook Time (Previous Frame) : 0.000 ms children GPU Cook Time (Previous Frame) : 0.000 ms
1 node with errors inside.
Error: Traceback (most recent call last):
File "/project1/TDDepthAnything/script1_callbacks", line 18, in onCook File "/project1/TDDepthAnything/DepthAnythingExt", line 80, in run AttributeError: 'DepthAnythingExt' object has no attribute 'stream' (/project1/TDDepthAnything/script1_callbacks)
1 stored item(s):
DefaultExtstored {'StoredProperty': None}
Extensions:
DepthAnythingExt:</project1/TDDepthAnything/DepthAnythingExt.DepthAnythingExt> (promoted)
/project1/TDDepthAnything/DepthAnythingExt:
class DepthAnythingExt class TopCUDAInterface class TopArrayInterface`

![image](https://github.com/user-attachments/assets/a0ec6985-9a80-4341-9bbc-b9cfd558f732)

**Comment by SaibotC** [comment]
requires tensorrt==9.0.1.post11.dev4 to be installed even outside the virtual environment
