### ISSUE TITLE
Error on .tox Init

### ISSUE THREAD

**Issue by ish-** [olegchomp/TDDepthAnything#3]
Hello!

Have problem with .tox component.
`accelerate.bat` has been running twice without errors.

```
DAT compile error: /project1/TDDepthAnything/DepthAnythingExt
Traceback (most recent call last):
  File "/project1/TDDepthAnything/DepthAnythingExt", line 1
    r = previousimport(*args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads/TDDepthAnything-main\.venv/Lib/site-packages\tensorrt\__init__.py", line 18
    from tensorrt_bindings import *
    r = previousimport(*args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads/TDDepthAnything-main\.venv/Lib/site-packages\tensorrt_bindings\__init__.py", line 141
    from .tensorrt import *
    r = previousimport(*args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tensorrt_bindings.tensorrt'

Error retrieving extension for /project1/TDDepthAnything: (Extension 1) td.tdError: Module compilation error. See /project1/TDDepthAnything/DepthAnythingExt for details.
Traceback (most recent call last):
  File "/project1/TDDepthAnything/script1_callbacks", line 18, in onCook
AttributeError: 'NoneType' object has no attribute 'run'`
```

Pulse btns gives the same error.

**Comment by olegchomp** [comment]
Can you try to load engine in TD?

**Comment by ish-** [comment]
Yes, as i said, any pulse button (e.g "load engine") gives the same error

**Comment by olegchomp** [comment]
Do you have multiple version of python installed? Your sys py version should be same as in TD.

**Comment by joansc** [comment]
I just had the same error and switching the sys python version to the same one as TD (3.11.1) solved the problem. I had to redo all the installation process :)

Joan

**Comment by ish-** [comment]
@joansc thank you!
