### ISSUE TITLE
"Torch not compiled with CUDA enabled" error

### ISSUE THREAD

**Issue by ChrisWatersDesign** [olegchomp/TDDepthAnything#9]
Hi there, I'm using Touchdesigner 23.11600 on Windows 10

Encountering the error below when adding the .tox to a project. 
```
Error retrieving extension for /project1/TDDepthAnything: (Extension 1)   File "/project1/TDDepthAnything/DepthAnythingExt", line 50, in __init__
  File "D:\TouchDesigner/Tox & Add Ons/TDDepthAnything-main/TDDepthAnything-main\.venv/Lib/site-packages\torch\cuda\__init__.py", line 305, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
  File "/project1/TDDepthAnything/parexec1"
AttributeError("'NoneType' object has no attribute 'num_bindings'") 
  (Debug - DAT:/project1/TDDepthAnything/DepthAnythingExt fn:__init__ line:47)
Traceback (most recent call last):
  File "/project1/TDDepthAnything/script1_callbacks", line 18, in onCook
AttributeError: 'NoneType' object has no attribute 'run'
python >>> 
```
Perhaps unrealted, I've tried to 'on Settings page change path to TDDepthAnything folder and click Re-init'. Please could you confirm the folder is the 'TDDepthAnything-main' folder path that I should be adding? 

Many thanks for your help, 

Chris

**Comment by olegchomp** [comment]
> raise AssertionError("Torch not compiled with CUDA enabled")

Did you set correct path to python 3.11 in accelerate.bat?

> Please could you confirm the folder is the 'TDDepthAnything-main' folder path that I should be adding?

It's correct

**Comment by ChrisWatersDesign** [comment]
Hi, thanks very much for your response. Yes I believe so, set as below:

set PYTHON_PATH= "C:\Users\Chris\AppData\Local\Programs\Python\Python311\python.exe"

**Comment by 8055WhiteDevil** [comment]
hey i have the same issue
